### ISSUE TITLE
Comment: শিখে কাজে লাগাবেন? নাকি কাজ করতে করতে শিখবেন? সময় কিভাবে বের করবেন?

### ISSUE THREAD

**Issue by ImaginativeShohag** [ImaginativeShohag/imaginativeshohag.github.io#7]
Link: https://imaginativeshohag.github.io/2021/08/17/learn-then-apply-or-apply-and-learn

_**⚠️ Note:** Ignore the `Closed` status of the issue, and please share your comment._

**Comment by moklesur644** [comment]
ভাইয়া আপনি কথা গুলো এত চমৎকার ভাবে গুছিয়ে বলছেন খুব ভালো লাগছে
